<?php
/**
 * @file
 * Code for the CT Post feature.
 */

include_once('cmtls_post.features.inc');

/**
 * Implements hook_cmtls_app
 * 
 * @see cmtls.module
 */
function cmtls_post_cmtls_app() {
  return array(
    'cmtls_post' => array(
      'title' => t('Posts'),
      'description' => t('Basic posts/articles'),
      'node types' => array(
        'cmtls_post' => t('Post'),
      ),
    ),
  );
}

/**
 * Implements hook_cmtls_app_config
 * 
 * @see cmtls.module
 */
function cmtls_post_cmtls_app_config($config) {
    
  $defaults = array(
    'sorting_field' => 'node_created',
    'sorting_dir' => 'DESC'
  );
  
  $settings = array_merge($defaults, isset($config['cmtls_post']) ? $config['cmtls_post'] : array());
  
  $form['cmtls_post'] = array(
    '#type' => 'fieldset',
    '#title' => t('Sorting settings'),
    '#collapsible' => TRUE,
    '#states' => array(
      'visible' => array(
        ':input[name="field_cmtls_app_type['.LANGUAGE_NONE.'][0][cmtls_app_type]"]' => array('value' => 'cmtls_post'),
      ),
    ),
  );

  $form['cmtls_post']['sorting_field'] = array(
    '#type' => 'radios',
    '#title' => t('Sorting field'),
    '#default_value' => $settings['sorting_field'],
    '#options' => array(
      'node_created' => t('Created date'),
      'node_title' => t('Article title'),
      'node_comment_statistics_last_comment_timestamp' => t('Last comment time'),
    ),
  );
  
  $form['cmtls_post']['sorting_dir'] = array(
    '#type' => 'radios',
    '#title' => t('Sorting order'),
    '#default_value' => $settings['sorting_dir'],
    '#options' => array(
      'ASC' => t('Ascending'),
      'DESC' => t('Descending'),
    ),
  );

  return $form;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * adds autocomplete for the location
 */
function cmtls_post_form_cmtls_post_node_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_js(drupal_get_path('module', 'cmtls_location') . '/js/cmtls.location_ac.js');
}

